development:
    database: book_time_development
    adapter: mysql
    encoding: utf8
    host: localhost
    username: root
    password:


test: &test
    database: book_time_test
    adapter: mysql
    encoding: utf8
    host: localhost
    username: root
    password:


production:
    database: book_time_production
    adapter: mysql
    encoding: utf8
    host: localhost
    username: root
    password:

cucumber:
  <<: *test

